<a href="https://colab.research.google.com/github/catafest/colab_google/blob/master/catafest_047.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a simple example how to use the RNN known as **recurrent neural networks**.

*Recurrent neural networks RNN are a class of neural networks that is powerful for modeling sequence data such as time series or natural language*.

You can read more on [wikipedia](https://en.wikipedia.org/wiki/Recurrent_neural_network).


Let's start with the import step for default python packages.

In [34]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers


Let's set the layers for this neural network.

In [35]:
units = 64
model = tf.keras.layers.SimpleRNN(
    units,
    activation="tanh",
    use_bias=True,
    kernel_initializer="glorot_uniform",
    recurrent_initializer="orthogonal",
    bias_initializer="zeros",
    kernel_regularizer=None,
    recurrent_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    recurrent_constraint=None,
    bias_constraint=None,
    dropout=0.0,
    recurrent_dropout=0.0,
    return_sequences=False,
    return_state=False,
    go_backwards=False,
    stateful=False,
    unroll=False,
    #**kwargs
)

Let run to create the *sequence_output*,and *final_state*.

In [36]:
inputs = np.random.random([32, 10, 8]).astype(np.float32)
simple_rnn = tf.keras.layers.SimpleRNN(4)

output = simple_rnn(inputs)

simple_rnn = tf.keras.layers.SimpleRNN(
    4, return_sequences=True, return_state=True)

sequence_output, final_state = simple_rnn(inputs)

Let's see the results:

The **sequence output**, often denoted as sequence_output, refers to the output of the RNN at each time step of the input sequence.

In a language model, for example, this could be the predicted probability distribution over the vocabulary for each word in the input sentence. For each time step, the RNN produces an output that might encode information about the current input and the previous hidden state. The sequence output is a sequence of vectors where each vector corresponds to the output at a specific time step.

In [37]:
print("sequence output",sequence_output)

sequence output tf.Tensor(
[[[-0.7376058  -0.27154022  0.6412025   0.26495436]
  [ 0.22019926 -0.8107417   0.11049154  0.3031098 ]
  [-0.21552336 -0.89441246  0.41979998 -0.39929935]
  ...
  [-0.8941558  -0.06466898  0.7695777   0.2538306 ]
  [-0.22761662 -0.0241184  -0.15276092  0.51853603]
  [-0.46362072 -0.6313244   0.82171834  0.30747953]]

 [[-0.24525905 -0.63860756  0.6035213  -0.67934316]
  [-0.6880303  -0.5356085  -0.47181994  0.08338848]
  [-0.7095654  -0.68703586  0.8514794  -0.00812948]
  ...
  [-0.87407583 -0.6574199   0.15843143 -0.31284106]
  [-0.756225   -0.31491488  0.41810307  0.6721497 ]
  [ 0.33724123 -0.41116393  0.59464574  0.39817914]]

 [[-0.5042844   0.09277479  0.16040711  0.2612613 ]
  [-0.43343642 -0.04361439  0.32401708  0.6387127 ]
  [ 0.20247814  0.41225934  0.45709464  0.24618687]
  ...
  [-0.1482535   0.8050526  -0.33205914 -0.613595  ]
  [-0.35629544  0.78723353  0.64315593 -0.41220254]
  [-0.42882958  0.5449506   0.5090625  -0.07940085]]

 ...

 [[-0.5

The **final state**, often referred to as final_state, is the hidden state of the RNN after processing the entire input sequence.

It represents the summarization of information learned from the entire sequence. In a language model, this final state might encapsulate the understanding of the entire sentence. This state can be used as an initial state when processing subsequent sequences, which can be useful for tasks like generating text sequentially.

In [38]:
print("final_state",final_state)

final_state tf.Tensor(
[[-0.46362072 -0.6313244   0.82171834  0.30747953]
 [ 0.33724123 -0.41116393  0.59464574  0.39817914]
 [-0.42882958  0.5449506   0.5090625  -0.07940085]
 [-0.88141346 -0.02122334  0.7353388   0.18726377]
 [-0.2506953  -0.38087377  0.11141878 -0.12674046]
 [-0.1683723   0.10109448  0.11104453 -0.06542716]
 [-0.09716203 -0.27717307  0.7385087  -0.46453968]
 [-0.52165544  0.7480989  -0.03952791  0.23496689]
 [ 0.25015426 -0.4475493   0.02783038 -0.35240418]
 [ 0.05104969 -0.72378385  0.09075148  0.14886816]
 [-0.37033442  0.15645869 -0.02744232 -0.01338587]
 [ 0.2573149  -0.9446309   0.47538492 -0.04427608]
 [ 0.5575325  -0.41781384 -0.4111579   0.05440567]
 [ 0.08964776 -0.1407861   0.82569563  0.5465532 ]
 [ 0.27345413 -0.28769118  0.545642   -0.01720521]
 [ 0.5370163  -0.92477083  0.37222436  0.42600414]
 [-0.45385018  0.32283455 -0.5329749   0.46791974]
 [-0.54584676 -0.8512721   0.6010319   0.01500216]
 [-0.05098296 -0.50335073  0.5520216  -0.21641147]
 [-0.169

In [39]:
print("Sequence output shape:", sequence_output.shape)
print("Final state shape:", final_state.shape)

Sequence output shape: (32, 10, 4)
Final state shape: (32, 4)


the next steps will depend on the specific task you are working on.

common scenarios:

*Sequence Classification* - to make a prediction.

*Sequence-to-Sequence Tasks* - to generating the target sequence step by step using techniques like beam search or sampling.

*Language Modeling and Text Generation* - generate the next word or token in the sequence or to predict the next word's probabilities.

*Transfer Learning* - for transfer learning to fine-tune the RNN.

*Feature Extraction* - for downstream tasks.

NOTE : Depending on the scenario you are using, you must have appropriate settings, see these settings for *Sequence-to-Sequence Tasks*:

`return_sequences=True, return_state=True`