<a href="https://colab.research.google.com/github/catafest/colab_google/blob/master/catafest_005.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Today I show you how to use the estimators.

Estimators are supported in TensorFlow 2.0.

Let's import the tensoflow and datasets

In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras.datasets import mnist

TensorFlow 2.x selected.


Let's see the version of tensoflow:

In [2]:

print(tf.__version__)

2.1.0


Loads the MNIST dataset and set the x_train and y_train and show these datasets.

In [3]:

mnist_train = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
print(x_train, y_train)
print('----------------------------')
print(x_test, y_test)


11493376/11490434 [==============================] - 0s 0us/step
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]

I create a simple model 

In [0]:
def make_model():
  return tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, 3, activation='relu',
                           kernel_regularizer=tf.keras.regularizers.l2(0.02),
                           input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(10)
  ])

The model can be compile and turn your model into an estimator. 

Take model with *make_model* and compile with the optimizer ...

The *estimator* is create with *model_to_estimator*

In [5]:

model = make_model()
# compile the model 
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
# create estimator with model
estimator = tf.keras.estimator.model_to_estimator(keras_model = model)

print(estimator)
# define the steps for each epoch
STEPS_PER_EPOCH = 5
# set the number of epoch 
NUM_EPOCHS = 10
# define the estimator's input_fn
def input_fn():
  datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)
  mnist_train, mnist_test = datasets['train'], datasets['test']

  BUFFER_SIZE = 10000
  BATCH_SIZE = 64

  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255

    return image, label[..., tf.newaxis]

  train_data = mnist_train.map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
  return train_data.repeat()

# Define train & eval specs
train_spec = tf.estimator.TrainSpec(input_fn=input_fn,
                                    max_steps=STEPS_PER_EPOCH * NUM_EPOCHS)
eval_spec = tf.estimator.EvalSpec(input_fn=input_fn,
                                  steps=STEPS_PER_EPOCH)




INFO:tensorflow:Using default config.
INFO:tensorflow:Using the Keras model provided.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmph88sz0m6', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_re

Let's create the Estimator

In [6]:
tf.estimator.EstimatorSpec(model)


EstimatorSpec(mode=<tensorflow.python.keras.engine.sequential.Sequential object at 0x7fc451e7cc50>, predictions={}, loss=None, train_op=None, eval_metric_ops={}, export_outputs=None, training_chief_hooks=(), training_hooks=(), scaffold=<tensorflow.python.training.monitored_session.Scaffold object at 0x7fc451a17550>, evaluation_hooks=(), prediction_hooks=())

In [7]:
tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)


INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.


local data directory. If you'd instead prefer to read directly from our public
GCS bucket (recommended if you're running on GCP), you can instead set
data_dir=gs://tfds-data/datasets.





Dataset mnist downloaded and prepared to /root/tensorflow_datasets/mnist/3.0.0. Subsequent calls will reuse this data.
INFO:tensorflow:Calling model_fn.


INFO:tensorflow:Calling model_fn.


INFO:tensorflow:Done calling model_fn.


INFO:tensorflow:Done calling model_fn.


INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='/tmp/tmph88sz0m6/keras/keras_model.ckpt', vars_to_warm_start='.*', var_name_to_vocab_info={}, var_name_to_prev_var_name={})


INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='/tmp/tmph88sz0m6/keras/keras_model.ckpt', vars_to_warm_start='.*', var_name_to_vocab_info={}, var_name_to_prev_var_name={})


INFO:tensorflow:Warm-starting from: /tmp/tmph88sz0m6/keras/keras_model.ckpt


INFO:tensorflow:Warm-starting from: /tmp/tmph88sz0m6/keras/keras_model.ckpt


INFO:tensorflow:Warm-starting variables only in TRAINABLE_VARIABLES.


INFO:tensorflow:Warm-starting variables only in TRAINABLE_VARIABLES.


INFO:tensorflow:Warm-started 8 variables.


INFO:tensorflow:Warm-started 8 variables.


INFO:tensorflow:Create CheckpointSaverHook.


INFO:tensorflow:Create CheckpointSaverHook.


INFO:tensorflow:Graph was finalized.


INFO:tensorflow:Graph was finalized.


INFO:tensorflow:Running local_init_op.


INFO:tensorflow:Running local_init_op.


INFO:tensorflow:Done running local_init_op.


INFO:tensorflow:Done running local_init_op.


INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmph88sz0m6/model.ckpt.


INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmph88sz0m6/model.ckpt.


INFO:tensorflow:loss = 2.465046, step = 0


INFO:tensorflow:loss = 2.465046, step = 0


INFO:tensorflow:Saving checkpoints for 50 into /tmp/tmph88sz0m6/model.ckpt.


INFO:tensorflow:Saving checkpoints for 50 into /tmp/tmph88sz0m6/model.ckpt.


INFO:tensorflow:Calling model_fn.


INFO:tensorflow:Calling model_fn.


INFO:tensorflow:Done calling model_fn.


INFO:tensorflow:Done calling model_fn.


INFO:tensorflow:Starting evaluation at 2020-03-17T16:48:51Z


INFO:tensorflow:Starting evaluation at 2020-03-17T16:48:51Z


INFO:tensorflow:Graph was finalized.


INFO:tensorflow:Graph was finalized.


INFO:tensorflow:Restoring parameters from /tmp/tmph88sz0m6/model.ckpt-50


INFO:tensorflow:Restoring parameters from /tmp/tmph88sz0m6/model.ckpt-50


INFO:tensorflow:Running local_init_op.


INFO:tensorflow:Running local_init_op.


INFO:tensorflow:Done running local_init_op.


INFO:tensorflow:Done running local_init_op.


INFO:tensorflow:Evaluation [1/5]


INFO:tensorflow:Evaluation [1/5]


INFO:tensorflow:Evaluation [2/5]


INFO:tensorflow:Evaluation [2/5]


INFO:tensorflow:Evaluation [3/5]


INFO:tensorflow:Evaluation [3/5]


INFO:tensorflow:Evaluation [4/5]


INFO:tensorflow:Evaluation [4/5]


INFO:tensorflow:Evaluation [5/5]


INFO:tensorflow:Evaluation [5/5]


INFO:tensorflow:Inference Time : 2.76601s


INFO:tensorflow:Inference Time : 2.76601s


INFO:tensorflow:Finished evaluation at 2020-03-17-16:48:54


INFO:tensorflow:Finished evaluation at 2020-03-17-16:48:54


INFO:tensorflow:Saving dict for global step 50: accuracy = 0.759375, global_step = 50, loss = 1.3734324


INFO:tensorflow:Saving dict for global step 50: accuracy = 0.759375, global_step = 50, loss = 1.3734324


INFO:tensorflow:Saving 'checkpoint_path' summary for global step 50: /tmp/tmph88sz0m6/model.ckpt-50


INFO:tensorflow:Saving 'checkpoint_path' summary for global step 50: /tmp/tmph88sz0m6/model.ckpt-50


INFO:tensorflow:Loss for final step: 0.43079564.


INFO:tensorflow:Loss for final step: 0.43079564.


({'accuracy': 0.759375, 'global_step': 50, 'loss': 1.3734324}, [])