<a href="https://colab.research.google.com/github/catafest/colab_google/blob/master/catafest_037.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

If you set the TPU device for your colab notebook from **Runtime > Change runtime type > Hardware accelerator > TPU** then is no need to install with **pip tool** the tensorflow python module.

In [ ]:
import tensorflow as tf
import os
import tensorflow_datasets as tfds

*Keras is the high-level API of TensorFlow 2: an approachable, highly-productive interface for solving machine learning problems, with a focus on modern deep learning. It provides essential abstractions and building blocks for developing and shipping machine learning solutions with high iteration velocity.*
Let's test on optimizer from keras. 


Using the basic model architecture Sequential I train a basic **model** with data : 

`tf.random.normal((1000, 5))`

In Keras, **model.compile** is a method that configures the learning process of a model. It takes three important arguments:

**optimizer**: This argument specifies the optimizer used for training the model, such as Stochastic Gradient Descent (SGD), Adam, or Adagrad.

**loss**: This argument specifies the loss function used to evaluate the performance of the model. Examples of loss functions include mean squared error, categorical cross-entropy, and binary cross-entropy.

**metrics**: This argument specifies the evaluation metric used to judge the quality of the model's predictions during training and testing. Examples of metrics include accuracy, precision, and recall.

In [ ]:
# define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=(5,), activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# compile the model with an optimizer, a loss function, and a metric
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = [tf.keras.metrics.BinaryAccuracy()]

model.compile(optimizer=optimizer, loss=loss_fn, metrics=metrics)

# train the model on some data
x_train = tf.random.normal((1000, 5))
print("x_train : ",x_train)
y_train = tf.random.uniform((1000, 1), minval=0, maxval=2, dtype=tf.int32)
model.fit(x_train, y_train, epochs=10, batch_size=32)
#print("y_train : ",y_train) 
#y_train :  tf.Tensor([[1] [0] [0] ...

x_train :  tf.Tensor(
[[ 0.9437875  -1.175582    0.4352783  -0.3842272  -0.9783649 ]
 [ 0.7195584  -0.7591996   1.3462368   0.8319625   0.7515625 ]
 [-0.4320674   0.3568053  -0.22778086  0.34535506 -0.5609262 ]
 ...
 [-0.49610403 -0.5109574   0.24627769 -1.1905332  -0.23388018]
 [-0.16958141  2.0091386   1.1448544  -0.10147487  1.1585898 ]
 [-1.2264752  -0.5240709   0.03711427  1.3515667   0.27160376]], shape=(1000, 5), dtype=float32)
Epoch 1/10
32/32 [==============================] - 1s 3ms/step - loss: 0.7949 - binary_accuracy: 0.4740
Epoch 2/10
32/32 [==============================] - 0s 3ms/step - loss: 0.7726 - binary_accuracy: 0.4770
Epoch 3/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7574 - binary_accuracy: 0.4760
Epoch 4/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7466 - binary_accuracy: 0.4820
Epoch 5/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7389 - binary_accuracy: 0.4820
Epoch 6/10
32/32 [==================

I can evaluate this model using:
 `model.evaluate`

In [ ]:
# Test the model on some new data
x_test = tf.random.normal((10, 5))
y_test = tf.random.uniform((10, 1), minval=0, maxval=2, dtype=tf.int32)

# Evaluate the model on the test data
test_loss, test_acc = model.evaluate(x_test, y_test)

# Print result
print('Test accuracy:', test_acc)
print("Test Loss:", test_loss)



1/1 [==============================] - 0s 133ms/step - loss: 0.7285 - binary_accuracy: 0.5000
Test accuracy: 0.5
Test Loss: 0.7285147309303284


In [ ]:
print(dir(tf.keras.optimizers))

['Adadelta', 'Adagrad', 'Adam', 'Adamax', 'Ftrl', 'Nadam', 'Optimizer', 'RMSprop', 'SGD', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_sys', 'deserialize', 'experimental', 'get', 'legacy', 'schedules', 'serialize']


In [ ]:
# define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=(5,), activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])



In [ ]:
# compile the model with AdaFactor optimizer and binary cross-entropy loss
model.compile(optimizer=tf.keras.optimizers.Adadelta(),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])

# generate random data for training
x_train = tf.random.normal((1000, 5))
y_train = tf.random.uniform((1000, 1), minval=0, maxval=2, dtype=tf.int32)

# train the model on the data
model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
32/32 [==============================] - 1s 2ms/step - loss: 0.7703 - accuracy: 0.4860
Epoch 2/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7703 - accuracy: 0.4860
Epoch 3/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7702 - accuracy: 0.4860
Epoch 4/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7702 - accuracy: 0.4870
Epoch 5/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7702 - accuracy: 0.4870
Epoch 6/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7701 - accuracy: 0.4870
Epoch 7/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7701 - accuracy: 0.4870
Epoch 8/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7701 - accuracy: 0.4870
Epoch 9/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7700 - accuracy: 0.4870
Epoch 10/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7700 - accuracy: 0.4870


In [ ]:
# Test the model on some new data
x_test = tf.random.normal((10, 5))
y_test = tf.random.uniform((10, 1), minval=0, maxval=2, dtype=tf.int32)

# Evaluate the model on the test data
test_loss, test_acc = model.evaluate(x_test, y_test)

# Print result
print('Test accuracy:', test_acc)
print("Test Loss:", test_loss)

1/1 [==============================] - 0s 124ms/step - loss: 0.7483 - accuracy: 0.4000
Test accuracy: 0.4000000059604645
Test Loss: 0.7483202815055847


This source code let you use the last tensorflow implementation for **Adafactor** optimizer 

In [ ]:
import tensorflow as tf
# create an Adafactor optimizer
opt = tf.keras.optimizers.experimental.Adafactor(learning_rate=0.001)

# define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=(5,), activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
# compile the model with the Adafactor optimizer
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

# train the model on some data
x_train = tf.random.normal((1000, 5))
y_train = tf.random.uniform((1000, 1), minval=0, maxval=2, dtype=tf.int32)
model.fit(x_train, y_train, epochs=10, batch_size=32)
# Test the model on some new data
x_test = tf.random.normal((10, 5))
y_test = tf.random.uniform((10, 1), minval=0, maxval=2, dtype=tf.int32)

# Evaluate the model on the test data
test_loss, test_acc = model.evaluate(x_test, y_test)

# Print result
print('Test accuracy:', test_acc)
print("Test Loss:", test_loss)

Epoch 1/10
32/32 [==============================] - 4s 11ms/step - loss: 0.7254 - accuracy: 0.4970
Epoch 2/10
32/32 [==============================] - 0s 10ms/step - loss: 0.7217 - accuracy: 0.5000
Epoch 3/10
32/32 [==============================] - 0s 9ms/step - loss: 0.7184 - accuracy: 0.5040
Epoch 4/10
32/32 [==============================] - 1s 22ms/step - loss: 0.7154 - accuracy: 0.5070
Epoch 5/10
32/32 [==============================] - 0s 9ms/step - loss: 0.7128 - accuracy: 0.5080
Epoch 6/10
32/32 [==============================] - 0s 14ms/step - loss: 0.7106 - accuracy: 0.5060
Epoch 7/10
32/32 [==============================] - 1s 19ms/step - loss: 0.7086 - accuracy: 0.5100
Epoch 8/10
32/32 [==============================] - 0s 10ms/step - loss: 0.7067 - accuracy: 0.5080
Epoch 9/10
32/32 [==============================] - 0s 12ms/step - loss: 0.7052 - accuracy: 0.5110
Epoch 10/10
1/1 [==============================] - 1s 636ms/step - loss: 0.7729 - accuracy: 0.3000
Test accurac

The **wurlitzer** package is a tool for capturing and displaying the output of external processes in the Jupyter notebook interface or other Python environments. 

In [ ]:
!pip install wurlitzer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import wurlitzer
import subprocess

with wurlitzer.sys_pipes():
    # Run a command that produces C-level stdout/stderr output
    output = subprocess.check_output(['ls', '-la'])
    
print(output.decode())
with wurlitzer.sys_pipes():
    # Run a command that produces C-level stdout/stderr output
    output2 = subprocess.check_output(['uname', '-a'])
print(output2.decode())

total 16
drwxr-xr-x 1 root root 4096 Feb 23 14:38 .
drwxr-xr-x 1 root root 4096 Feb 25 14:57 ..
drwxr-xr-x 4 root root 4096 Feb 23 14:37 .config
drwxr-xr-x 1 root root 4096 Feb 23 14:38 sample_data

Linux f3139351f18b 5.10.147+ #1 SMP Sat Dec 10 16:00:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux



The other optimizers can be tested similarly:
*   Stochastic Gradient Descent (SGD)
*   Adam
*   Adagrad
*   Adadelta
*   RMSprop

... or the others added, see the new implementation:
https://www.youtube.com/watch?v=ZWOccJ3LZAw 